# Generated by Django 3.0.1 on 2020-02-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200213_1823'),
        ('orders', '0002_productinorder_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cust_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cust_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cust_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.AddField(
            model_name='order',
            name='fathername',
            field=models.TextField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='prods',
            field=models.ManyToManyField(blank=True, default=None, related_name='prod', to='products.Variable'),
        ),
        migrations.AddField(
            model_name='order',
            name='secondname',
            field=models.TextField(default=None, max_length=30),
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
