# Generated by Django 3.0.1 on 2020-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200218_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fathername',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='secondname',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
