# Generated by Django 3.0.1 on 2020-02-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200219_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
