# Generated by Django 3.0.1 on 2020-02-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200219_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
