# Generated by Django 3.0.1 on 2020-02-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200219_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
