# Generated by Django 3.0.1 on 2020-02-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200219_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adress',
        ),
        migrations.AddField(
            model_name='order',
            name='adres',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
