# Generated by Django 3.0.1 on 2020-02-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200219_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prods',
        ),
        migrations.RemoveField(
            model_name='order',
            name='secondname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
    ]
