# Generated by Django 3.0.1 on 2020-02-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200219_1742'),
        ('orders', '0009_auto_20200219_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=None, max_length=40)),
                ('name', models.CharField(default=None, max_length=20)),
                ('secondname', models.CharField(default=None, max_length=30)),
                ('fathername', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adres', models.CharField(default=None, max_length=30)),
                ('prods', models.ManyToManyField(blank=True, default=None, related_name='prod', to='products.Variable')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
