# Generated by Django 3.0.1 on 2020-02-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200219_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oder',
        ),
    ]
