# Generated by Django 3.0.1 on 2020-02-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0021_auto_20200219_1742'),
        ('orders', '0011_delete_oder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=None, max_length=40)),
                ('name', models.CharField(default=None, max_length=20)),
                ('secondname', models.CharField(default=None, max_length=20)),
                ('fathname', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(default=None, max_length=20)),
                ('prods', models.ManyToManyField(blank=True, default=None, related_name='prod', to='products.Variable')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
