# Generated by Django 3.0.1 on 2020-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200219_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comm',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
