# Generated by Django 3.0.1 on 2020-01-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200129_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fimage',
            field=models.ImageField(height_field='300', upload_to='media/product_images/', width_field='300'),
        ),
    ]
