# Generated by Django 3.0.1 on 2020-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200129_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fimage',
            field=models.ImageField(upload_to='media/product_images/'),
        ),
    ]
