# Generated by Django 3.0.1 on 2020-02-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200203_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='colors', to='products.ProductColor'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
