# Generated by Django 3.0.1 on 2020-02-04 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200205_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimg',
            old_name='products',
            new_name='color',
        ),
        migrations.AddField(
            model_name='productimg',
            name='prod',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product'),
        ),
    ]
