# Generated by Django 3.0.1 on 2020-02-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200205_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimg',
            name='prod',
        ),
    ]
