# Generated by Django 3.0.1 on 2020-02-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productimg_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='prods',
        ),
        migrations.RemoveField(
            model_name='productimg',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='prod',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='color', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productimg',
            name='colors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='products.Color'),
        ),
        migrations.AddField(
            model_name='productimg',
            name='prods',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='products.Product'),
        ),
        migrations.AddField(
            model_name='variable',
            name='prods',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
