# Generated by Django 3.0.1 on 2020-02-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200205_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='prod',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='color', to='products.Color'),
        ),
    ]
