# Generated by Django 3.0.1 on 2020-02-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productimg_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'размер',
                'verbose_name_plural': 'размеры',
            },
        ),
        migrations.RemoveField(
            model_name='variable',
            name='size',
        ),
        migrations.AddField(
            model_name='variable',
            name='size',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='color', to='products.Size'),
        ),
    ]
