# Generated by Django 3.0.1 on 2020-02-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200205_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'verbose_name': 'характеристика', 'verbose_name_plural': 'характеристики'},
        ),
        migrations.AddField(
            model_name='size',
            name='info',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
