# Generated by Django 3.0.1 on 2020-02-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200205_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'verbose_name': 'Количество размеров', 'verbose_name_plural': 'Количество размеров'},
        ),
        migrations.RemoveField(
            model_name='variable',
            name='size',
        ),
        migrations.AddField(
            model_name='variable',
            name='size',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='products.Size'),
        ),
    ]
