# Generated by Django 3.0.1 on 2020-02-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200213_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'verbose_name': 'Все товары', 'verbose_name_plural': 'Все товары'},
        ),
    ]
