# Generated by Django 3.0.1 on 2020-03-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200219_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fimage',
            field=models.ImageField(default=1, upload_to='media/category_images/'),
            preserve_default=False,
        ),
    ]
